export const initialState = [
  {
    name: "name",
    type: "text",
    value: "",
    required: true,
    description: "Please enter name",
    touched: false,
    status: "",
  },
  {
    name: "image",
    type: "file",
    value: "",
    required: false,
    description: "Please select image",
    touched: false,
    status: "",
  },
  {
    name: "email",
    type: "email",
    value: "",
    required: true,
    description: "Please enter your email id",
    touched: false,
    status: "",
  },
  {
    name: "password",
    type: "password",
    value: "",
    required: true,
    description: "Please enter your password",
    touched: false,
    status: "",
  },
  {
    name: "contactNumber",
    type: "text",
    value: "",
    required: false,
    description: "Please enter your contact number",
    touched: false,
    status: "",
  },
  {
    name: "role",
    type: "select",
    value: "Customer",
    required: false,
    description: "Please select role",
    touched: false,
    status: "",
  },
  {
    name: "status",
    type: "select",
    value: "active",
    required: false,
    description: "Please select status",
    touched: false,
    status: "",
  },
];
export const initialStateRegister = [
  {
    name: "name",
    type: "text",
    value: "",
    required: true,
    description: "Please enter name",
    touched: false,
    status: "",
  },
  {
    name: "email",
    type: "email",
    value: "",
    required: true,
    description: "Please enter your email id",
    touched: false,
    status: "",
  },
  {
    name: "password",
    type: "password",
    value: "",
    required: true,
    description: "Please enter your password",
    touched: false,
    status: "",
  },
];
